name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bundle:
    runs-on: ubuntu-latest
    name: Build JS Bundles
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: "./.yarn/cache"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: |
          yarn build
          yarn run capacitor sync

  android:
    runs-on: ubuntu-latest
    name: Build Android
    needs: bundle
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: |
        cd android/
        ./gradlew build

