name: Releases
on:
  push:
    branches:
      - 'main'

  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
  # pull_request_target event is required for autolabeler to support PRs from forks
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  versions:
    name: Update Releases
    runs-on: ubuntu-latest
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Draft Release
        id: release
        # Drafts your next Release notes as Pull Requests are merged into "main"
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update project versions
        id: version
        run: |
          echo "Next Version: ${{ steps.release.outputs.tag_name }}"
          npm version ${{ steps.release.outputs.tag_name }}

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump project version to ${{ steps.release.outputs.tag_name }}
          file_pattern: "package.json"
