name: Releases
on:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  versions:
    name: Update Releases
    runs-on: ubuntu-latest
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Draft Release
        id: release
        # Drafts your next Release notes as Pull Requests are merged into "main"
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update project versions
        id: version
        run: |
          echo "Next Version: ${{ steps.release.outputs.tag_name }}"
          npm version ${{ steps.release.outputs.tag_name }}

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump project version to ${{ steps.release.outputs.tag_name }}
          file_pattern: "package.json"
